#index:
#    path: /
#    controller: App\Controller\DefaultController::index

home:
    path: /
    controller: App\Controller\HomeController::index
    

photos:
    path: /photos
    controller: App\Controller\PropertyController::index


